export const criticalIncidents = [
  {
    id: 1,
    location: "Arizona Border Region",
    country: "USA",
    lat: 32.2226,
    lng: -110.9747,
    type: "violence",
    severity: "high",
    date: "2026-05",
    description: "Reported violent incident involving migrants near a border transit route.",
    source: "Verified news report",
    verified: true,
  },
  {
    id: 2,
    location: "Mediterranean Crossing",
    country: "International Waters",
    lat: 35.0,
    lng: 18.0,
    type: "dangerous_route",
    severity: "high",
    date: "2026-04",
    description: "Multiple fatalities reported during sea crossing.",
    source: "NGO report",
    verified: true,
  },
  {
    id: 3,
    location: "Florida",
    country: "USA",
    lat: 27.6648,
    lng: -81.5158,
    type: "policy_pressure",
    severity: "medium",
    date: "2026-05",
    description: "Policy environment and public discourse increasing uncertainty for immigrant communities.",
    source: "ACLU / policy reports",
    verified: true,
  },
  {
    id: 4,
    location: "Texas Border Region",
    country: "USA",
    lat: 26.2034,
    lng: -98.2300,
    type: "enforcement",
    severity: "high",
    date: "2026-05",
    description: "Heightened enforcement activity and reported migrant vulnerability.",
    source: "NGO + field reports",
    verified: true,
  }
];