/**
 * Payment Readiness Configuration
 *
 * When Stripe Payment Links are ready, set these environment variables in Vercel:
 *
 * NEXT_PUBLIC_STRIPE_DONATION_LINK
 * NEXT_PUBLIC_STRIPE_INDIVIDUAL_MEMBERSHIP_LINK
 * NEXT_PUBLIC_STRIPE_ORGANIZATION_MEMBERSHIP_LINK
 * NEXT_PUBLIC_STRIPE_CELEBRATION_FEE_LINK
 * NEXT_PUBLIC_STRIPE_SPONSORSHIP_LINK
 * NEXT_PUBLIC_STRIPE_PASSPORT_INTEREST_LINK
 * NEXT_PUBLIC_STRIPE_NON_MEMBER_CELEBRATION_FEE_LINK
 *
 * Until then, CTAs route to registration/contact pages.
 *
 * Revenue Policy (Universal — applies to all Member Organizations equally):
 * - Donations generated by a Member Org: 95% to org, 5% MundusPASS/Mundus.Center
 * - Individual membership fees generated by a Member Org: 95% to org, 5% service fee
 * - Organization membership fees generated by a Member Org: 95% to org, 5% service fee
 * - Merchant registration fees: 50% to registering/referring org, 50% Mundus.Center
 * - Merchant monthly fees: 50% to registering/referring org, 50% Mundus.Center
 * - 1% of members' MundusPASS purchases → member's org
 * - Passport to the World card sales: 50% to seller, 25% to IA, 25% to Mundus.Center
 * - Settlement target: within 24 hours, subject to processor configuration
 */

export const paymentLinks = {
  donation: process.env.NEXT_PUBLIC_STRIPE_DONATION_LINK || '/contact',
  individualMembership: process.env.NEXT_PUBLIC_STRIPE_INDIVIDUAL_MEMBERSHIP_LINK || '/register',
  organizationMembership: process.env.NEXT_PUBLIC_STRIPE_ORGANIZATION_MEMBERSHIP_LINK || '/register-organization',
  celebrationFee: process.env.NEXT_PUBLIC_STRIPE_CELEBRATION_FEE_LINK || '/contact',
  sponsorship: process.env.NEXT_PUBLIC_STRIPE_SPONSORSHIP_LINK || '/contact',
  passportInterest: process.env.NEXT_PUBLIC_STRIPE_PASSPORT_INTEREST_LINK || '/contact',
  nonMemberCelebrationFee: process.env.NEXT_PUBLIC_STRIPE_NON_MEMBER_CELEBRATION_FEE_LINK || '/contact',
};

export const isPaymentLive = (key: keyof typeof paymentLinks): boolean => {
  const envKey = `NEXT_PUBLIC_STRIPE_${key.replace(/([A-Z])/g, '_$1').toUpperCase()}_LINK`;
  return Boolean(process.env[envKey]);
};

/**
 * Celebration Date Logic
 * Starting 2027: first Saturday of June through second Saturday of June
 */
export function getCelebrationDates(year: number): { start: Date; end: Date } | null {
  if (year < 2027) return null;
  const june1 = new Date(year, 5, 1); // June 1
  const dayOfWeek = june1.getDay(); // 0=Sun..6=Sat
  const firstSaturday = 1 + ((6 - dayOfWeek + 7) % 7);
  const start = new Date(year, 5, firstSaturday);
  const end = new Date(year, 5, firstSaturday + 7);
  return { start, end };
}

export function formatCelebrationRange(year: number): string {
  const dates = getCelebrationDates(year);
  if (!dates) return '';
  const opts: Intl.DateTimeFormatOptions = { month: 'long', day: 'numeric' };
  return `${dates.start.toLocaleDateString('en-US', opts)} through ${dates.end.toLocaleDateString('en-US', opts)}, ${year}`;
}
